name: Nodejs-Real-Test-Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project code
      uses: actions/checkout@v4

    - name: Setup Node.js Env
      uses: actions/setup-node@v4
      with:
        node-version: '22' 

    - name: Install Express Package
      run: npm install express

    - name: Run Real Unit Test
      run: node test.js